import React from "react";
import Navigation from "../shared/Navigation";
import { Text, Column, Subtitle } from "../../theme/index";
import styled from "styled-components";
import Footer from "../shared/Footer";

const Wrapper = styled.div`
  width: 100%;
  display: flex;
  background: #fff;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: ${props => props.height};
`;

const StyledColumn = styled(Column)`
  width: 55%
  margin: 2em 0 4em 0;
  padding: 1em 0;
  text-align: center;
  align-items: center;
  @media (max-width: 780px) {
   width: 95%;
  }
`;

export default function Prviacy() {
  return (
    <Wrapper>
      <Navigation />
      <StyledColumn>
        <Subtitle>Privacy Policy</Subtitle>
        <Text>
          Effective date: January 27, 2019 FeedForward ("us", "we", or "our")
          operates the FeedForward mobile application (hereinafter referred to
          as the "Service"). This page informs you of our policies regarding the
          collection, use and disclosure of personal data when you use our
          Service and the choices you have associated with that data. We use
          your data to provide and improve the Service. By using the Service,
          you agree to the collection and use of information in accordance with
          this policy. Unless otherwise defined in this Privacy Policy, the
          terms used in this Privacy Policy have the same meanings as in our
          Terms and Conditions. Definitions • Service Service is the FeedForward
          mobile application operated by FeedForward • Personal Data Personal
          Data means data about a living individual who can be identified from
          those data (or from those and other information either in our
          possession or likely to come into our possession). • Usage Data Usage
          Data is data collected automatically either generated by the use of
          the Service or from the Service infrastructure itself (for example,
          the duration of a page visit). • Cookies Cookies are small files
          stored on your device (computer or mobile device). Information
          Collection and Use We collect several different types of information
          for various purposes to provide and improve our Service to you. Types
          of Data Collected Personal Data While using our Service, we may ask
          you to provide us with certain personally identifiable information
          that can be used to contact or identify you ("Personal Data").
          Personally identifiable information may include, but is not limited
          to: • Email address • First name and last name • Cookies and Usage
          Data We may use your Personal Data to contact you with newsletters,
          marketing or promotional materials and other information that may be
          of interest to you. You may opt out of receiving any, or all, of these
          communications from us by following the unsubscribe link or the
          instructions provided in any email we send. Usage Data When you access
          the Service with a mobile device, we may collect certain information
          automatically, including, but not limited to, the type of mobile
          device you use, your mobile device unique ID, the IP address of your
          mobile device, your mobile operating system, the type of mobile
          Internet browser you use, unique device identifiers and other
          diagnostic data ("Usage Data"). Tracking & Cookies Data We use cookies
          and similar tracking technologies to track the activity on our Service
          and we hold certain information. Cookies are files with a small amount
          of data which may include an anonymous unique identifier. Cookies are
          sent to your browser from a website and stored on your device. Other
          tracking technologies are also used such as beacons, tags and scripts
          to collect and track information and to improve and analyse our
          Service. You can instruct your browser to refuse all cookies or to
          indicate when a cookie is being sent. However, if you do not accept
          cookies, you may not be able to use some portions of our Service.
          Examples of Cookies we use: • Session Cookies. We use Session Cookies
          to operate our Service. • Preference Cookies. We use Preference
          Cookies to remember your preferences and various settings. • Security
          Cookies. We use Security Cookies for security purposes. Use of Data
          FeedForward uses the collected data for various purposes: • To provide
          and maintain our Service • To notify you about changes to our Service
          • To allow you to participate in interactive features of our Service
          when you choose to do so • To provide customer support • To gather
          analysis or valuable information so that we can improve our Service •
          To monitor the usage of our Service • To detect, prevent and address
          technical issues • To provide you with news, special offers and
          general information about other goods, services and events which we
          offer that are similar to those that you have already purchased or
          enquired about unless you have opted not to receive such information
          Transfer of Data Your information, including Personal Data, may be
          transferred to â€” and maintained on â€” computers located outside of
          your state, province, country or other governmental jurisdiction where
          the data protection laws may differ from those of your jurisdiction.
          If you are located outside United States and choose to provide
          information to us, please note that we transfer the data, including
          Personal Data, to United States and process it there. Your consent to
          this Privacy Policy followed by your submission of such information
          represents your agreement to that transfer. FeedForward will take all
          the steps reasonably necessary to ensure that your data is treated
          securely and in accordance with this Privacy Policy and no transfer of
          your Personal Data will take place to an organisation or a country
          unless there are adequate controls in place including the security of
          your data and other personal information. Disclosure of Data Legal
          Requirements FeedForward may disclose your Personal Data in the good
          faith belief that such action is necessary to: • To comply with a
          legal obligation • To protect and defend the rights or property of
          FeedForward • To prevent or investigate possible wrongdoing in
          connection with the Service • To protect the personal safety of users
          of the Service or the public • To protect against legal liability
          Security of Data The security of your data is important to us but
          remember that no method of transmission over the Internet or method of
          electronic storage is 100% secure. While we strive to use commercially
          acceptable means to protect your Personal Data, we cannot guarantee
          its absolute security. Service Providers We may employ third party
          companies and individuals to facilitate our Service ("Service
          Providers"), provide the Service on our behalf, perform
          Service-related services or assist us in analysing how our Service is
          used. These third parties have access to your Personal Data only to
          perform these tasks on our behalf and are obligated not to disclose or
          use it for any other purpose. Links to Other Sites Our Service may
          contain links to other sites that are not operated by us. If you click
          a third party link, you will be directed to that third party's site.
          We strongly advise you to review the Privacy Policy of every site you
          visit. We have no control over and assume no responsibility for the
          content, privacy policies or practices of any third party sites or
          services. Children's Privacy Our Service does not address anyone under
          the age of 18 ("Children"). We do not knowingly collect personally
          identifiable information from anyone under the age of 18. If you are a
          parent or guardian and you are aware that your Child has provided us
          with Personal Data, please contact us. If we become aware that we have
          collected Personal Data from children without verification of parental
          consent, we take steps to remove that information from our servers.
          Changes to This Privacy Policy We may update our Privacy Policy from
          time to time. We will notify you of any changes by posting the new
          Privacy Policy on this page. We will let you know via email and/or a
          prominent notice on our Service, prior to the change becoming
          effective and update the "effective date" at the top of this Privacy
          Policy. You are advised to review this Privacy Policy periodically for
          any changes. Changes to this Privacy Policy are effective when they
          are posted on this page. Contact Us If you have any questions about
          this Privacy Policy, please contact us: • By email:
          karim@feedforwardhealth.com
        </Text>
      </StyledColumn>
      <Footer />
    </Wrapper>
  );
}
